using System;
namespace Game.Logic.Protocol
{
	public enum eFightPackageType
	{
		RSAKey,
		LOGIN,
		SEND_TO_GAME,
		CHAT = 19,
		DISCONNECT = 83,
		SYS_NOTICE = 3,
		CHANGE_GAME_TYPE = 73,
		SEND_TO_USER = 32,
		SEND_GAME_PLAYER_ID,
		DISCONNECT_PLAYER,
		PLAYER_ON_GAME_OVER,
		PLAYER_USE_PROP_INGAME,
		PLAYER_ADD_ITEM,
		PLAYER_ADD_GOLD,
		PLAYER_ADD_GP,
		PLAYER_ONKILLING_LIVING,
		PLAYER_ONMISSION_OVER,
		PLAYER_CONSORTIAFIGHT,
		PLAYER_SEND_CONSORTIAFIGHT,
		PLAYER_REMOVE_GOLD,
		PLAYER_REMOVE_MONEY,
		PLAYER_ADD_TEMPLATE,
		PLAYER_ADD_TEMPLATE1 = 48,
		PLAYER_REMOVE_GP,
		PLAYER_REMOVE_OFFER,
		ROOM_CREATE = 64,
		ROOM_REMOVE,
		ROOM_START_GAME,
		SEND_TO_ROOM,
		ROOM_STOP_GAME,
		FIND_CONSORTIA_ALLY,
		PLAYER_ADD_MONEY,
		PLAYER_ADD_GIFTTOKEN,
		PLAYER_ADD_MEDAL
	}
}
