using System;
namespace Game.Logic
{
	public enum AddMoneyType
	{
		Auction = 1,
		Mail,
		Shop,
		Marry,
		Consortia,
		Item,
		Charge,
		Award,
		Box,
		Game,
		Auction_Update = 101,
		Mail_Money = 201,
		Mail_Pay,
		Mail_Send,
		Shop_Buy = 301,
		Shop_Continue,
		Shop_Card,
		Shop_Present,
		Marry_Spark = 401,
		Marry_Stage,
		Marry_Gift,
		Marry_Follow,
		Marry_Unmarry,
		Marry_Room,
		Marry_RoomAdd,
		Marry_Flower,
		Marry_Hymeneal = 410,
		Consortia_Rich = 412,
		Item_Move = 601,
		Item_Color,
		Charge_RMB = 701,
		Award_Daily = 801,
		Award_Quest,
		Award_Drop,
		Award_Answer,
		Award_BossDrop,
		Award_TakeCard,
		Box_Open = 901,
		Game_Boos = 1001,
		Game_PaymentTakeCard,
		Game_TryAgain,
		Game_Other,
		Game_Shoot
	}
}
