using System;
namespace Game.Server.Packets
{
	public enum ActivityPackageType
	{
		EVERYDAYACTIVEPOINT_DATA = 1,
		EVERYDAYACTIVEPOINT_CHANGE,
		USEMONEYPOINT_COMPLETE,
		GETACTIVEPOINT_REWARD,
		REUSEMONEYPOINT_COMPLETE,
		REGETACTIVEPOINT_REWARD,
		ADD_ACTIVITY_DATA_CHANGE
	}
}
