using System;
namespace Game.Server.Packets
{
	public enum GameRoomPackageType
	{
		GAME_ROOM_CREATE,
		GAME_ROOM_LOGIN,
		GAME_ROOM_SETUP_CHANGE,
		GAME_ROOM_KICK,
		GAME_ROOM_ADDPLAYER,
		GAME_ROOM_REMOVEPLAYER,
		GAME_TEAM,
		GAME_START,
		ROOMLIST_UPDATE = 9,
		GAME_ROOM_UPDATE_PLACE,
		GAME_PICKUP_CANCEL,
		GAME_PICKUP_STYLE,
		GAME_PICKUP_WAIT,
		ROOM_PASS,
		GAME_PLAYER_STATE_CHANGE,
		GAME_ROOM_FULL = 17,
		PASSED_WARRIORSARENA_10 = 34,
		No_WARRIORSARENA_TICKET,
		LAST_MISSION_FOR_WARRIORSARENA = 33,
		SINGLE_ROOM_BEGIN = 18
	}
}
