using System;
namespace Game.Server.Packets
{
	public enum NewChickenBoxPackageType
	{
		ENTERCHICKENVIEW = 10,
		USEEAGLEEYE,
		TAKEOVERCARD = 13,
		FLUSHCHICKENVIEW,
		CLICKSTARTBNT,
		AllITEMSHOW = 12,
		CHICKENBOXOPEN = 1,
		CHICKENBOXCLOSE,
		GETITEMLIST,
		CANCLICKCARD = 5,
		TACKOVERCARD = 4,
		EAGLEEYE = 7,
		OVERSHOWITEMS = 6
	}
}
