using System;
namespace Game.Server.Packets
{
	public enum WorldBossPackageType
	{
		OPEN,
		OVER,
		CANENTER,
		MOVE = 6,
		ENTER = 3,
		WORLDBOSS_EXIT,
		WORLDBOSS_PLAYERSTAUTSUPDATE = 7,
		WORLDBOSS_FIGHTOVER,
		WORLDBOSS_ROOM_CLOSE,
		WORLDBOSS_BLOOD_UPDATE = 5,
		WORLDBOSS_RANKING = 10,
		WORLDBOSS_PLAYER_REVIVE,
		WORLDBOSS_BUYBUFF
	}
}
